project_name: flashpaper
env:
    - GITHUB_USER={{ if index .Env "GITHUB_USER"  }}{{ .Env.GITHUB_USER }}{{ else }}tkalus-forks{{ end }}
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      -
        goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
-
  image_templates: ["ghcr.io/{{ .Env.GITHUB_USER }}/{{.ProjectName}}:{{ .Version }}-amd64"]
  goarch: amd64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
-
  image_templates: ["ghcr.io/{{ .Env.GITHUB_USER }}/{{.ProjectName}}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
-
  name_template: ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8
-
  name_template: ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8
